# cdp1 = int(input())
# nmp1 = int(input())
# vup1 = float(input())
# cdp2 = int(input())
# nmp2 = int(input())
# vup2 = float(input())
# pc1 = nmp1*vup1
# pc2 = nmp2*vup2
# total = pc1+pc2
# print("TOTAL A PAGAR = R$ ""%.2f"%total)
pcum = input().split(" ")
pcdois = input().split(" ")
nmp1 = int(pcum[1])
vup1 = float(pcum[2])
nmp2 = int(pcdois[1])
vup2 = float(pcdois[2])
pc1 = nmp1*vup1
pc2 = nmp2*vup2
total = pc1+pc2
print("TOTAL A PAGAR = R$ ""%.2f"%total)
